import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navLinks = [
  { href: "/", label: "Home" },
  { href: "/services", label: "Services" },
  { href: "/about", label: "About" },
  { href: "/contact", label: "Contact" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = typeof window !== 'undefined' ? window.location.pathname : "/";
  return (
    <html lang="en">
      <body className="bg-tech-primary text-tech-secondary min-h-screen flex flex-col">
        <nav className="w-full sticky top-0 z-50 bg-tech-primary/95 shadow-md border-b border-tech-accent/20">
          <div className="max-w-6xl mx-auto flex items-center justify-between px-6 py-3">
            <Link href="/" className="flex items-center gap-2 text-2xl font-bold text-tech-accent">
              <span className="inline-block w-8 h-8 bg-tech-accent rounded-full mr-2"></span>
              Sonoma-System
            </Link>
            <div className="flex gap-6 items-center text-lg font-semibold">
              {navLinks.map(link => (
                <Link
                  key={link.href}
                  href={link.href}
                  className={`hover:text-tech-highlight transition-colors pb-1 border-b-2 ${pathname === link.href ? 'border-tech-accent text-tech-accent' : 'border-transparent'}`}
                >
                  {link.label}
                </Link>
              ))}
            </div>
          </div>
        </nav>
        <main className="flex-1 w-full max-w-6xl mx-auto px-4 sm:px-8 py-8">{children}</main>
        <footer className="w-full bg-tech-primary border-t border-tech-accent/20 py-6 mt-12">
          <div className="max-w-6xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4 px-6">
            <div className="flex items-center gap-2 text-tech-accent font-bold text-lg">
              <span className="inline-block w-6 h-6 bg-tech-accent rounded-full"></span>
              Sonoma-System
            </div>
            <div className="flex gap-6 text-tech-secondary/80 text-sm">
              <Link href="/services" className="hover:text-tech-accent">Services</Link>
              <Link href="/about" className="hover:text-tech-accent">About</Link>
              <Link href="/contact" className="hover:text-tech-accent">Contact</Link>
            </div>
            <div className="flex gap-4">
              <a href="https://linkedin.com" target="_blank" rel="noopener" className="hover:text-tech-accent" aria-label="LinkedIn">
                <svg width="24" height="24" fill="currentColor" className="inline"><path d="M19 0h-14c-2.76 0-5 2.24-5 5v14c0 2.76 2.24 5 5 5h14c2.76 0 5-2.24 5-5v-14c0-2.76-2.24-5-5-5zm-11 19h-3v-9h3v9zm-1.5-10.28c-.97 0-1.75-.79-1.75-1.75s.78-1.75 1.75-1.75 1.75.79 1.75 1.75-.78 1.75-1.75 1.75zm13.5 10.28h-3v-4.5c0-1.08-.02-2.47-1.5-2.47-1.5 0-1.73 1.17-1.73 2.39v4.58h-3v-9h2.89v1.23h.04c.4-.75 1.38-1.54 2.84-1.54 3.04 0 3.6 2 3.6 4.59v4.72z"/></svg>
              </a>
              <a href="mailto:info@sonoma-system.com" className="hover:text-tech-accent" aria-label="Email">
                <svg width="24" height="24" fill="currentColor" className="inline"><path d="M12 13.065l-11.99-7.065v14h24v-14l-12.01 7.065zm11.99-9.065h-23.98l11.99 7.065 11.99-7.065z"/></svg>
              </a>
            </div>
          </div>
          <div className="text-center text-tech-secondary/60 text-xs mt-4">&copy; {new Date().getFullYear()} Sonoma-System. All rights reserved.</div>
        </footer>
      </body>
    </html>
  );
}
